# Generated by Django 5.1.15 on 2026-09-18 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_data', models.JSONField(help_text='Snapshot JSON con nombre, email, teléfono, empresa, cargo, notas, etc.', verbose_name='Datos Ingresados por el Visitante')),
                ('consent_accepted', models.BooleanField(default=True, verbose_name='Consentimiento de Privacidad Aceptado')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='Navegador / Dispositivo')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP (Anónima)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Intercambio')),
            ],
            options={
                'verbose_name': 'Intercambio de Contacto',
                'verbose_name_plural': 'Intercambios de Contacto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de la Etiqueta')),
                ('color', models.CharField(default='blue', max_length=25, verbose_name='Color hexadecimal o badge class')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('BIT_SCANNED', 'NFC Scanned / QR Read'), ('PROFILE_VIEWED', 'Digital Profile Viewed'), ('FORM_SUBMITTED', 'Exchange Form Submitted'), ('CONTACT_CREATED', 'CRM Contact Created')], db_index=True, max_length=30, verbose_name='Tipo de Evento')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos Adicionales')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y Hora')),
                ('bit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='bits.bit', verbose_name='Dispositivo BIT')),
            ],
            options={
                'verbose_name': 'Evento de Analítica',
                'verbose_name_plural': 'Eventos de Analítica',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre y Apellidos')),
                ('empresa', models.CharField(blank=True, max_length=150, verbose_name='Empresa')),
                ('cargo', models.CharField(blank=True, max_length=150, verbose_name='Cargo / Especialidad')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=35, verbose_name='Teléfono')),
                ('whatsapp', models.CharField(blank=True, max_length=35, verbose_name='WhatsApp Directo')),
                ('estado', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Contactado', 'Contactado'), ('Interesado', 'Interesado'), ('Propuesta', 'Propuesta Enviada'), ('Cliente', 'Cliente / Cerrado')], db_index=True, default='Nuevo', max_length=25, verbose_name='Estado en el Pipeline CRM')),
                ('origen', models.CharField(default='BIT / Networking NFC', max_length=100, verbose_name='Canal de Captura')),
                ('notas', models.TextField(blank=True, verbose_name='Notas de Seguimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Captura')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('bit_origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_contacts', to='bits.bit', verbose_name='BIT de Origen')),
            ],
            options={
                'verbose_name': 'Contacto CRM',
                'verbose_name_plural': 'Contactos CRM',
                'ordering': ['-created_at'],
            },
        ),
    ]
