# Generated by Django 5.1.15 on 2026-09-18 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bits', '0002_initial'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Propietario CRM'),
        ),
        migrations.AddField(
            model_name='contactexchange',
            name='bit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='bits.bit', verbose_name='Dispositivo BIT de Origen'),
        ),
        migrations.AddField(
            model_name='contacttag',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contacttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_contacts', to='crm.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='contacttag',
            unique_together={('contact', 'tag')},
        ),
    ]
