# Generated by Django 5.1.15 on 2026-09-18 16:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, error_messages={'unique': 'Ya existe un usuario registrado con este correo electrónico.'}, max_length=255, unique=True, verbose_name='correo electrónico')),
                ('is_staff', models.BooleanField(default=False, help_text='Indica si el usuario puede iniciar sesión en el sitio de administración.', verbose_name='es staff')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si esta cuenta debe ser tratada como activa.', verbose_name='activo')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de registro')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, verbose_name='Nombre completo')),
                ('cargo', models.CharField(blank=True, max_length=150, verbose_name='Cargo / Puesto')),
                ('empresa', models.CharField(blank=True, max_length=150, verbose_name='Empresa u Organización')),
                ('descripcion', models.TextField(blank=True, verbose_name='Biografía / Descripción')),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='profiles/avatars/', verbose_name='Fotografía de perfil')),
                ('fotografia_url', models.URLField(blank=True, help_text='URL directa opcional si no se sube archivo local', verbose_name='URL de Fotografía alternativa')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email público de contacto')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp con prefijo internacional')),
                ('redes_sociales', models.JSONField(blank=True, default=dict, help_text='Mapeo de clave/url para redes sociales', verbose_name='Redes sociales')),
                ('links', models.JSONField(blank=True, default=list, help_text='Lista de enlaces destacados y portafolio', verbose_name='Enlaces adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
    ]
