# Generated by Django 5.1.15 on 2026-09-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BIT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_interno', models.CharField(help_text='Identificador serial de fabricación. Ej: BIT-000001', max_length=50, unique=True, verbose_name='ID Hardware Interno')),
                ('token_publico', models.CharField(db_index=True, help_text='Token Base62 aleatorio de 8 a 10 caracteres grabado en el chip NFC / QR', max_length=12, unique=True, verbose_name='Token Público NanoID')),
                ('status', models.CharField(choices=[('Unassigned', 'Sin Asignar'), ('Active', 'Activo'), ('Inactive', 'Inactivo')], db_index=True, default='Unassigned', max_length=20, verbose_name='Estado del Dispositivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Dispositivo BIT',
                'verbose_name_plural': 'Dispositivos BIT',
                'ordering': ['-created_at'],
            },
        ),
    ]
